# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Tasks for the Task runner:
#
# https://taskfile.dev

version: "3"

silent: true

includes:
  docs: docs
  pre-commit: tasks/pre-commit
  project: tasks/project
  py: tasks/python
  venv: tasks/uv-developer

tasks:
  default:
    cmds:
      - task: list

  bootstrap:
    desc: Set up environment for development
    aliases: [setup]
    cmds:
      - task: pre-commit:setup

  clean:
    desc: Delete generated files
    cmds:
      - task: docs:clean
      - task: project:clean

  doc:
    desc: Display documentation in a Web browser
    cmds:
      - task: docs:serve

  fmt:
    desc: Format code
    aliases: [format]
    cmds:
      - task: py:fmt

  lint:
    desc: Run all checks
    aliases: [check]
    cmds:
      - task: pre-commit:check

  list:
    desc: List available tasks
    cmds:
      - task --list

  test:
    desc: Run tests
    cmds:
      - task: pre-commit:run
        vars: { HOOK_ID: "ruff-format" }
      - task: pre-commit:run
        vars: { HOOK_ID: "ruff" }
      - task: pre-commit:run
        vars: { HOOK_ID: "mypy" }
      - task: py:test
