# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for the Task runner
#
# See: https://taskfile.dev

version: "3"

silent: true

includes:
  docs: tasks/mkdocs
  pre-commit: tasks/pre-commit
  project: tasks/project
  py:lint: tasks/ruff
  py:test: tasks/pytest
  venv: tasks/uv

tasks:
  default:
    cmds:
      - task: list

  bootstrap:
    desc: Set up environment for development
    aliases: [setup]
    cmds:
      - task: pre-commit:setup

  clean:
    desc: Delete generated files
    cmds:
      - task: project:clean
      - task: docs:clean
      - task: py:lint:clean

  fmt:
    desc: Format code
    aliases: [format]
    cmds:
      - task: py:lint:fmt

  lint:
    desc: Run all checks
    aliases: [check]
    cmds:
      - task: pre-commit:check

  list:
    desc: List available tasks
    cmds:
      - task --list

  test:
    desc: Run tests
    cmds:
      - task: pre-commit:run
        vars: { HOOK_ID: "ruff-format" }
      - task: pre-commit:run
        vars: { HOOK_ID: "ruff" }
      - task: pre-commit:run
        vars: { HOOK_ID: "mypy" }
      - task: py:test

  update:
    desc: Update
    cmds:
      - task: venv:update-reqs
      - task: venv:sync
